### ISSUE TITLE
Locale properties and certain files not being found in Jquery with Django

### ISSUE THREAD

**Issue by allison9y** [meshesha/officetohtml#1]
I am getting the 404 errors for locale properties, pdf.worker.js when running it in Django.  The pdf.worker.js is in the same director with pdf.js but it seems pdf.js requires the locale.properties and pdf.worker.js in a certain directory like /include/.... 

The files are placed in the static folder such as app/static/app/css or js. Do those files have to be placed in a certain way? How can those be worked around in this case?

**Comment by meshesha** [comment]
I do not know the Django framework , but I'm working on this issue, so there will be some flexibility in the location of files and folders. Meanwhile,  for the app to work, try to keep the folder order as in the example : [https://officetohtml.js.org/pages/demos.html](https://officetohtml.js.org/pages/demos.html)

![default](https://user-images.githubusercontent.com/18533793/52094215-f3782380-25c6-11e9-8ac6-26316201edb8.png)
